// HindiAnimeStuff — catalog data
// Each entry links to the official platform that distributes that title.
const ANIME_DATA = [
   {
  id: "chainsaw-man-reze-arc-movie",
  title: "Chainsaw Man - The Movie: Reze Arc",
  season: "Movie",
  thumb: "https://webp.iwebp.store/webp/280-380-3x-img.iwebp.store/images/imagecloud/poster_4481.png",
  genres: ["Animation", "Action", "Romance", "Fantasy"],
  run: "Movie (2025)",
  runtime: "1 hr 40 min",
  language: "Hindi · English",
  episodes: null,
  subtitle: "English",
  quality: "HD",
  rating: "?",
  platform: "FilesDL",
  platformUrl: "https://new6.filesdl.top/cloud/aMfFHgJSc0",
  synopsis: "Denji's life takes an unexpected turn after meeting the mysterious Reze. As romance blossoms, hidden secrets and deadly enemies emerge, forcing Chainsaw Man into one of his most emotional and explosive battles yet."
},
   {
  id: "suzume-2022",
  title: "Suzume",
  season: "Movie",
  thumb: "https://webp.iwebp.store/webp/280-380-3x-img.iwebp.store/images/imagecloud/poster_3025.png",
  genres: ["Animation", "Drama", "Adventure", "Fantasy"],
  run: "Movie (2022)",
  runtime: "2 hr 02 min",
  language: "Hindi · English",
  episodes: null,
  subtitle: "English",
  quality: "BluRay HD",
  rating: "7.6",
  platform: "FilesDL",
  platformUrl: "https://new6.filesdl.top/cloud/YKCoF7Spj3",
  synopsis: "A high school girl named Suzume embarks on a journey across Japan to close mysterious doors that unleash devastating disasters upon the world."
},
{
  id: "your-name-2016",
  title: "Your Name.",
  season: "Movie",
  thumb: "https://webp.iwebp.store/webp/280-380-3x-img.iwebp.store/images/imagecloud/poster_3751.png",
  genres: ["Animation", "Romance", "Drama"],
  run: "Movie (2016)",
  runtime: "1 hr 46 min",
  language: "Hindi · English",
  episodes: null,
  subtitle: "English",
  quality: "BluRay HD",
  rating: "8.9",
  platform: "FilesDL",
  platformUrl: "https://new6.filesdl.top/cloud/BzlG40T16R",
  synopsis: "Two teenagers mysteriously begin swapping bodies across time and distance, forming a deep connection as they search for each other across fate itself."
},
{
  id: "karna-the-guardian-s1",
  title: "Karna the Guardian",
  season: "Season 1",
  thumb: "https://iili.io/BtcMirv.jpg",
  genres: ["Action", "Adventure", "Fantasy"],
  run: "TV Series (2026)",
  runtime: "22 min",
  language: "Hindi · Tamil · Telugu · English",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "?",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Karna the Guardian Season 1-Hindi-Tamil-Telugu-English",
  synopsis: "Karna lives an ordinary life until the ancient demon Kalimba escapes and corrupts the world. After his mother is infected by the darkness, Karna awakens as the legendary Balancer and must master his powers to restore harmony before it's too late."
},
{
  id: "overflow-s1",
  title: "Overflow",
  season: "Season 1",
  thumb: "https://i.ibb.co/Pvk14bQ6/zmo-MA9-Lx.jpg",
  genres: ["Harem", "Hentai"],
  run: "ONA (2020)",
  runtime: "7 min",
  language: "Hindi · English · Japanese",
  episodes: 8,
  subtitle: "English",
  quality: "720p",
  rating: "8.6",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Overflow%20Season%201%20Hindi%20Dubbed",
  synopsis: "A college student's peaceful life is thrown into chaos when his two childhood friends unexpectedly move in, leading to a series of comedic and romantic misunderstandings."
},
{
  id: "skeleton-knight-in-another-world-s1",
  title: "Skeleton Knight in Another World",
  season: "Season 1",
  thumb: "https://iili.io/CfOwlCQ.jpg",
  genres: ["Action", "Adventure", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p AVC",
  rating: "7.2",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Skeleton Knight in Another World Season 1 Hindi",
  synopsis: "A gamer awakens inside his favorite MMORPG as a powerful skeleton knight and sets out to protect the innocent while searching for a way home."
},
{
  id: "an-adventurers-daily-grind-at-age-29-s1",
  title: "An Adventurer's Daily Grind at Age 29",
  season: "Season 1",
  thumb: "https://iili.io/fibrMUN.jpg",
  genres: ["Adventure", "Fantasy"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "6.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=An Adventurer’s Daily Grind at Age 29 Season 1 Hindi",
  synopsis: "A veteran adventurer nearing thirty discovers that experience and determination can be just as valuable as raw talent while taking on new quests."
},
{
  id: "strongest-exorcist-s1",
  title: "The Reincarnation of the Strongest Exorcist in Another World",
  season: "Season 1",
  thumb: "https://i.imgur.com/yeTVVCX.jpg",
  genres: ["Action", "Adventure", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "720p",
  rating: "7.1",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=The Reincarnation of the Strongest Exorcist in Another World Season 1 Hindi",
  synopsis: "After being betrayed, history's strongest exorcist is reincarnated into another world where he plans to live peacefully, but his overwhelming power once again draws him into conflict."
},
{
  id: "daemons-of-the-shadow-realm-s1",
  title: "Daemons of the Shadow Realm",
  season: "Season 1",
  thumb: "https://iili.io/BzgeD4R.jpg",
  genres: ["Action", "Adventure", "Fantasy"],
  run: "TV Series (2026)",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 24,
  subtitle: "English",
  quality: "720p",
  rating: "?",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Daemons of the Shadow Realm Season 1 Hindi",
  synopsis: "Twin siblings Yuru and Asa become entangled in an ancient conflict after discovering their connection to powerful supernatural Daemons that could determine the fate of their world."
},
{
  id: "gantz-s1",
  title: "Gantz",
  season: "Season 1",
  thumb: "https://iili.io/C3pAsuR.jpg",
  genres: ["Action", "Drama", "Horror", "Sci-Fi"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "720p AVC",
  rating: "7.1",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Gantz%20Season%201%20Hindi",
  synopsis: "After dying in a train accident, Kei Kurono and Masaru Kato are forced into deadly missions by a mysterious black sphere known as Gantz."
},
{
  id: "gantz-s2",
  title: "Gantz",
  season: "Season 2",
  thumb: "https://iili.io/C7kF0Sn.jpg",
  genres: ["Action", "Drama", "Horror", "Sci-Fi"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "720p AVC",
  rating: "7.1",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Gantz%20Season%202%20Hindi",
  synopsis: "The survivors continue fighting brutal alien missions while uncovering more of Gantz's deadly secrets and impossible rules."
},
{
  id: "devil-may-cry-s2",
  title: "Devil May Cry",
  season: "Season 2",
  thumb: "https://iili.io/BbV1JRe.jpg",
  genres: ["Action", "Adventure", "Fantasy", "Mystery"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English",
  episodes: 8,
  subtitle: "English · Hindi",
  quality: "720p",
  rating: "?",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Devil%20May%20Cry%20Season%202%20Hindi",
  synopsis: "Dante returns for another supernatural adventure, taking on dangerous demonic threats while uncovering new mysteries surrounding the underworld."
},
{
  id: "blue-box-s1",
  title: "Blue Box",
  season: "Season 1",
  thumb: "https://iili.io/CRp8j2e.jpg",
  genres: ["Comedy", "Drama", "Romance", "School", "Sports"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 25,
  subtitle: "English",
  quality: "720p AVC",
  rating: "8.2",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Blue%20Box%20Season%201%20Hindi",
  synopsis: "A badminton player's quiet crush on a basketball star turns into an inspiring coming-of-age story as they begin living under the same roof."
},
{
  id: "strongest-magician-demon-lords-army-s1",
  title: "The Strongest Magician in the Demon Lord's Army Was a Human",
  season: "Season 1",
  thumb: "https://i.imgur.com/Lo3kULV.jpeg",
  genres: ["Action", "Adventure", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "6.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=The%20Strongest%20Magician%20in%20the%20Demon%20Lords%20Army%20Was%20a%20Human%20Season%201%20Hindi",
  synopsis: "A powerful magician serving the Demon Lord hides a secret that could change the balance between humans and demons forever."
},
{
  id: "my-status-as-an-assassin-s1",
  title: "My Status as an Assassin Obviously Exceeds the Hero's",
  season: "Season 1",
  thumb: "https://i.imgur.com/Ojh8Jzx.jpeg",
  genres: ["Action", "Adventure", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "?",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=My%20Status%20as%20an%20Assassin%20Obviously%20Exceeds%20the%20Heros%20Season%201%20Hindi",
  synopsis: "Summoned to another world, an ordinary student discovers his assassin abilities far surpass those of the chosen hero."
},
{
  id: "watari-kun-s1",
  title: "Watari-kun's Is About to Collapse",
  season: "Season 1",
  thumb: "https://iili.io/Coe9CIS.jpg",
  genres: ["Comedy", "Drama", "Romance", "School", "Harem"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 26,
  subtitle: "English",
  quality: "720p",
  rating: "6.8",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Watari-kuns%20Is%20About%20to%20Collapse%20Season%201%20Hindi",
  synopsis: "Naoto Watari's peaceful school life begins to fall apart when a girl from his past suddenly reappears."
},
{
  id: "dr-stone-s3",
  title: "Dr. Stone: New World",
  season: "Season 3",
  thumb: "https://i.imgur.com/TpvFuGg.jpeg",
  genres: ["Adventure", "Comedy", "Shounen"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 22,
  subtitle: "English",
  quality: "720p",
  rating: "8.0",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Dr.%20Stone%20Season%203%20Hindi",
  synopsis: "Senku and the Kingdom of Science set sail on a global expedition to uncover the mystery behind humanity's petrification."
},
{
  id: "dr-stone-s4",
  title: "Dr. Stone: Science Future",
  season: "Season 4",
  thumb: "https://i.imgur.com/1Oj5RDF.jpeg",
  genres: ["Adventure", "Comedy", "Shounen"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 37,
  subtitle: "English",
  quality: "720p",
  rating: "6.7",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Dr.%20Stone%20Season%204%20Hindi",
  synopsis: "The final chapter begins as Senku's team races across the globe toward humanity's greatest scientific breakthrough."
},
{
  id: "campfire-cooking-s1",
  title: "Campfire Cooking in Another World with My Absurd Skill",
  season: "Season 1",
  thumb: "https://i.imgur.com/YtE6mb8.jpeg",
  genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.6",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Campfire%20Cooking%20in%20Another%20World%20with%20My%20Absurd%20Skill%20Season%201",
  synopsis: "Summoned to another world, Mukoda discovers that his unique Online Grocery skill is far more powerful than it first appears, leading him on a delicious adventure with legendary companions."
},
{
  id: "campfire-cooking-s2",
  title: "Campfire Cooking in Another World with My Absurd Skill",
  season: "Season 2",
  thumb: "https://iili.io/KpXSTyF.md.jpg",
  genres: ["Adventure", "Comedy", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.7",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Campfire%20Cooking%20in%20Another%20World%20with%20My%20Absurd%20Skill%20Season%202",
  synopsis: "Mukoda's relaxing journey continues as he discovers new lands, prepares incredible meals, and encounters even stronger mythical creatures."
},
{
  id: "scarlet-2025",
  title: "Scarlet",
  season: "Movie",
  thumb: "https://iili.io/B4Wyxwu.jpg",
  genres: ["Adventure", "Drama", "Fantasy"],
  run: "Movie (2025)",
  runtime: "1 hr 51 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: null,
  subtitle: "English",
  quality: "480p / 720p / 1080p",
  rating: "8.9",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Scarlet%20(2025)%20Hindi",
  synopsis: "A breathtaking fantasy adventure follows a courageous young heroine whose journey through a magical world will shape the fate of everyone around her."
},
{
  id: "your-name",
  title: "Your Name",
  season: "Movie",
  thumb: "https://iili.io/fcyFF99.jpg",
  genres: ["Adventure", "Drama", "Fantasy", "Romance"],
  run: "Movie",
  runtime: "1 hr 46 min",
  language: "Hindi · English · Japanese",
  episodes: null,
  subtitle: "English",
  quality: "480p / 720p / 1080p",
  rating: "8.9",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Your%20Name%20Hindi",
  synopsis: "Two teenagers mysteriously begin swapping bodies across time and distance, forming an unforgettable connection while racing to change fate."
},
   {
  id: "yuri-on-ice-s1",
  title: "Yuri on Ice",
  season: "Season 1",
  thumb: "https://iili.io/fb6SCGV.jpg",
  genres: ["Comedy", "Drama", "Sports", "Boys Love"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.5",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Yuri%20on%20Ice%20Season%201%20Hindi",
  synopsis: "After a crushing defeat, figure skater Yuri Katsuki gets a second chance when his idol Victor Nikiforov becomes his coach."
},
{
  id: "code-geass-s1",
  title: "Code Geass: Lelouch of the Rebellion",
  season: "Season 1",
  thumb: "https://i.imgur.com/HAhw8IK.jpg",
  genres: ["Action", "Drama"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 25,
  subtitle: "English",
  quality: "1080p",
  rating: "8.7",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Code%20Geass:%20Lelouch%20of%20the%20Rebellion%20Season%201%20Hindi",
  synopsis: "Exiled prince Lelouch gains the mysterious power of Geass and launches a rebellion against the Britannian Empire."
},
{
  id: "lookism-s1",
  title: "Lookism",
  season: "Season 1",
  thumb: "https://i.imgur.com/z5Ok5qV.jpg",
  genres: ["Action", "Drama", "Supernatural"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Korean",
  episodes: 8,
  subtitle: "English",
  quality: "720p",
  rating: "7.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Lookism%20Season%201%20Hindi",
  synopsis: "A bullied student suddenly wakes up in a handsome new body, forcing him to confront society's obsession with appearance."
},
{
  id: "viral-hit-s1",
  title: "Viral Hit",
  season: "Season 1",
  thumb: "https://i.imgur.com/aOwHi9S.jpeg",
  genres: ["Action", "Drama", "School"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.32",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Viral%20Hit%20Season%201%20Hindi",
  synopsis: "A timid high school student becomes an online sensation by learning how to fight through viral videos."
},
{
  id: "wistoria-s1",
  title: "Wistoria: Wand and Sword",
  season: "Season 1",
  thumb: "https://i.imgur.com/kZlH4ka.jpeg",
  genres: ["Action", "Adventure", "Fantasy", "School"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.8",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Wistoria:%20Wand%20and%20Sword%20Season%201%20Hindi",
  synopsis: "A swordsman with no magical talent enters a prestigious academy determined to fulfill a promise to his childhood friend."
},
{
  id: "wistoria-s2",
  title: "Wistoria: Wand and Sword",
  season: "Season 2",
  thumb: "https://iili.io/BLy4c0P.jpg",
  genres: ["Action", "Adventure", "Fantasy", "School"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "8.1",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Wistoria:%20Wand%20and%20Sword%20Season%202%20Hindi",
  synopsis: "Will Serfort continues his climb toward the top as new enemies and powerful magical challenges stand in his way."
},
{
  id: "the-angel-next-door-s1",
  title: "The Angel Next Door Spoils Me Rotten",
  season: "Season 1",
  thumb: "https://i.imgur.com/LNPhr5c.jpg",
  genres: ["Comedy", "Drama", "Romance"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.9",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=The%20Angel%20Next%20Door%20Spoils%20Me%20Rotten%20Season%201%20Hindi",
  synopsis: "A lonely high school boy's life changes after the school's most admired girl begins caring for him."
},
{
  id: "easygoing-territory-defense-s1",
  title: "Easygoing Territory Defense by the Optimistic Lord: Production Magic Turns a Nameless Village into the Strongest Fortified City",
  season: "Season 1",
  thumb: "https://iili.io/qCcmjK7.jpg",
  genres: ["Adventure", "Fantasy", "Isekai"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "6.9",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Easygoing%20Territory%20Defense%20by%20the%20Optimistic%20Lord%20Season%201%20Hindi",
  synopsis: "An optimistic young lord uses production magic to transform a remote village into a thriving fortified city."
},
{
  id: "dr-stone-s1",
  title: "Dr. Stone",
  season: "Season 1",
  thumb: "https://i.imgur.com/oYDoope.jpeg",
  genres: ["Adventure", "Comedy", "Shounen"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 24,
  subtitle: "English",
  quality: "720p",
  rating: "8.2",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Dr.%20Stone%20Season%201%20Hindi",
  synopsis: "Thousands of years after humanity is petrified, scientific genius Senku sets out to rebuild civilization from scratch."
},
{
  id: "dr-stone-s2",
  title: "Dr. Stone: Stone Wars",
  season: "Season 2",
  thumb: "https://i.imgur.com/IrPyaUl.jpeg",
  genres: ["Adventure", "Comedy", "Shounen"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 11,
  subtitle: "English",
  quality: "720p",
  rating: "8.2",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Dr.%20Stone%20Season%202%20Hindi",
  synopsis: "Senku's Kingdom of Science faces Tsukasa's Empire in a battle where knowledge becomes the ultimate weapon."
},
   {
  id: "my-dress-up-darling-s1",
  title: "My Dress-Up Darling",
  season: "Season 1",
  thumb: "https://i.imgur.com/CZAJLc0.jpg",
  genres: ["Comedy", "Romance"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "1080p",
  rating: "8.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=My%20Dress-Up%20Darling%20Season%2001%20Hindi",
  synopsis: "A quiet doll maker and a cheerful cosplay enthusiast form an unlikely friendship that blossoms through their shared passion for craftsmanship."
},
{
  id: "my-dress-up-darling-s2",
  title: "My Dress-Up Darling",
  season: "Season 2",
  thumb: "https://i.imgur.com/Az1rogM.jpeg",
  genres: ["Comedy", "Romance"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "1080p",
  rating: "8.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=My%20Dress-Up%20Darling%20Season%2002%20Hindi",
  synopsis: "Gojo and Marin continue creating elaborate cosplay outfits while their bond grows stronger with every new project."
},
{
  id: "oshi-no-ko-s1",
  title: "Oshi no Ko",
  season: "Season 1",
  thumb: "https://iili.io/CBtI2Eu.jpg",
  genres: ["Drama", "Music", "Mystery"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 11,
  subtitle: "English",
  quality: "480p / 720p / 1080p",
  rating: "8.6",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Oshi%20no%20Ko%20Season%2001%20Hindi",
  synopsis: "After a shocking tragedy, two siblings enter the entertainment industry to uncover the truth behind their mother's death."
},
{
  id: "bucchigiri-s1",
  title: "BUCCHIGIRI?!",
  season: "Season 1",
  thumb: "https://i.imgur.com/tamGfCB.jpeg",
  genres: ["Action", "Comedy", "Fantasy"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi Dubbed",
  episodes: 12,
  subtitle: "English",
  quality: "480p / 720p / 1080p",
  rating: "6.9",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=BUCCHIGIRI%20official%20Hindi%20Dubbed",
  synopsis: "A transfer student is dragged into supernatural gang battles where friendships and rivalries collide."
},
{
  id: "mob-psycho-100-s1",
  title: "Mob Psycho 100",
  season: "Season 1",
  thumb: "https://i.imgur.com/Py4Kkqv.jpeg",
  genres: ["Action", "Comedy", "Supernatural"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "480p / 720p / 1080p",
  rating: "8.49",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Mob%20Psycho%20100%20Season%201%20Hindi",
  synopsis: "A powerful psychic middle schooler struggles to control his emotions while living an ordinary life."
},
{
  id: "mob-psycho-100-s2",
  title: "Mob Psycho 100",
  season: "Season 2",
  thumb: "https://iili.io/C2gqXJR.jpg",
  genres: ["Action", "Comedy", "Supernatural"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Japanese",
  episodes: 14,
  subtitle: "English",
  quality: "480p / 720p / 1080p",
  rating: "8.49",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Mob%20Psycho%20100%20Season%202%20Hindi",
  synopsis: "Mob faces stronger espers and dangerous spirits while learning what it truly means to grow as a person."
},
{
  id: "my-happy-marriage-s1",
  title: "My Happy Marriage",
  season: "Season 1",
  thumb: "https://i.imgur.com/SQ1oCLZ.jpeg",
  genres: ["Drama", "Fantasy", "Romance"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "1080p",
  rating: "7.7",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=My%20Happy%20Marriage%20Season%201%20Hindi",
  synopsis: "A mistreated young woman begins a new life after an arranged marriage with a seemingly cold military commander."
},
{
  id: "my-happy-marriage-s2",
  title: "My Happy Marriage",
  season: "Season 2",
  thumb: "https://i.imgur.com/KOwg1rB.jpeg",
  genres: ["Drama", "Fantasy", "Romance"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "1080p",
  rating: "7.6",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=My%20Happy%20Marriage%20Season%202%20Hindi",
  synopsis: "As Miyo embraces her newfound happiness, greater supernatural threats begin to test her strength and relationships."
},
  {
    id: "overlord-s1",
    title: "Overlord",
    season: "Season 1",
    thumb: "https://i.imgur.com/Lznc1Mc.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Japanese · Hindi Dub",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p / 480p",
    rating: "7.9",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Overlord%20Season%2001",
    synopsis: "A veteran gamer finds himself trapped in his favorite MMORPG as his powerful in-game character, ruling a world that has suddenly become disturbingly real."
  },
  {
    id: "overlord-s2",
    title: "Overlord",
    season: "Season 2",
    thumb: "https://i.imgur.com/bLY5cXU.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p",
    rating: "7.8",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Overlord%20Season%2002",
    synopsis: "Ainz Ooal Gown continues to expand his dominion, navigating politics, war, and the loyalty of his fiercely devoted guardians."
  },
  {
    id: "overlord-s3",
    title: "Overlord",
    season: "Season 3",
    thumb: "https://i.imgur.com/EjQoKYD.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p",
    rating: "7.7",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Overlord%20Season%2003",
    synopsis: "Ainz's empire grows as he turns his attention to the Lizardman tribes and a kingdom unprepared for what's coming."
  },
  {
    id: "overlord-s4",
    title: "Overlord",
    season: "Season 4",
    thumb: "https://i.imgur.com/Bs2hVbH.jpeg",
    genres: ["Animation", "Adventure", "Fantasy"],
    run: "TV Series (2015–2022)",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 13,
    subtitle: "English (Softcoded)",
    quality: "1080p / 720p",
    rating: "7.6",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Overlord%20Season%2004",
    synopsis: "The final season sees the Sorcerer Kingdom's influence reach its peak as old enemies and new threats converge."
  },
  {
    id: "arifureta-s1",
    title: "Arifureta: From Commonplace to World's Strongest",
    season: "Season 1",
    thumb: "https://iili.io/CfLGynS.jpg",
    genres: ["Animation", "Fantasy", "Romance"],
    run: "TV Series (2019–2025)",
    runtime: "24 min",
    language: "Japanese · English · Tamil · Telugu · Hindi Dub",
    episodes: 13,
    subtitle: "English Dialogue + Dubtitle (ASS, Softcoded)",
    quality: "720p HD",
    rating: "6.7",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Arifureta%20From%20Commonplace%20to%20Worlds%20Strongest%20Season%201",
    synopsis: "An ordinary student is transported to another world and left behind by his class, only to claw his way to power through a hostile labyrinth."
  },
  {
    id: "arifureta-s2",
    title: "Arifureta: From Commonplace to World's Strongest",
    season: "Season 2",
    thumb: "https://iili.io/C2Mdoxf.jpg",
    genres: ["Animation", "Fantasy", "Romance"],
    run: "TV Series (2019–2025)",
    runtime: "24 min",
    language: "Japanese · English · Tamil · Telugu · Hindi Dub",
    episodes: 13,
    subtitle: "English Dialogue + Dubtitle (ASS, Softcoded)",
    quality: "720p HD",
    rating: "6.6",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Arifureta%20From%20Commonplace%20to%20Worlds%20Strongest%20Season%202",
    synopsis: "Hajime and his party push deeper into a world of monsters and rival nations as stakes rise beyond the dungeon walls."
  },
  {
    id: "solo-leveling-s1",
    title: "Solo Leveling",
    season: "Season 1",
    thumb: "https://i.imgur.com/HPAScdZ.jpg",
    genres: ["Action", "Adventure"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi Dubbed",
    episodes: 12,
    subtitle: "English",
    quality: "720p HD",
    rating: "8.3",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Solo%20Leveling%20Season%2001%20Hindi%20Dubbed%20Download",
    synopsis: "The weakest hunter alive discovers a mysterious system that lets him grow stronger than anyone has ever imagined."
  },
  {
    id: "solo-leveling-s2",
    title: "Solo Leveling: Arise from the Shadow",
    franchise: "Solo Leveling",
    season: "Season 2",
    thumb: "https://i.imgur.com/H8plomd.jpeg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 13,
    subtitle: "English",
    quality: "480p / 720p / 1080p",
    rating: "8.4",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Solo%20Leveling%20Season%2002%20Hindi%20Dubbed%20Download",
    synopsis: "Sung Jinwoo rises through the ranks of hunters as the shadow monarch's true power begins to surface."
  },
  {
    id: "cheat-skill-s1",
    title: "I Got a Cheat Skill in Another World and Became Unrivaled in The Real World, Too",
    season: "Season 1",
    thumb: "https://i.imgur.com/tWzmtfU.jpg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 13,
    subtitle: "English",
    quality: "720p",
    rating: "6.4",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=I%20Got%20a%20Cheat%20Skill%20in%20Another%20World%20and%20Became%20Unrivaled%20in%20the%20Real%20World%20Season%201%20Hindi",
    synopsis: "A bullied student gains overwhelming power in another world, and brings it home to turn the tables on his old life."
  },
  {
    id: "bye-bye-earth-s1",
    title: "Bye Bye, Earth",
    season: "Season 1",
    thumb: "https://i.imgur.com/vHdxGdC.jpeg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 10,
    subtitle: "English",
    quality: "720p",
    rating: "6.7",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Bye%20Bye%20Earth%20Season%201%20Hindi",
    synopsis: "In a world split into kingdoms ruled by women, a wandering warrior searches for someone strong enough to challenge fate itself."
  },
  {
    id: "bye-bye-earth-s2",
    title: "Bye Bye, Earth",
    season: "Season 2",
    thumb: "https://i.imgur.com/asAS7WM.jpeg",
    genres: ["Action", "Adventure", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 10,
    subtitle: "English",
    quality: "720p",
    rating: "6.2",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Bye%20Bye%20Earth%20Season%202%20Hindi",
    synopsis: "The journey continues as old truths unravel and new alliances form on the road to the world's edge."
  },
  {
    id: "ranma-s1",
    title: "Ranma ½ (2024)",
    season: "Season 1",
    thumb: "https://i.imgur.com/t1gAPCV.jpeg",
    genres: ["Action", "Comedy", "Romance"],
    run: "TV Series (2024)",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "7.8",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Ranma%20½%20Season%201%20Hindi",
    synopsis: "A martial artist cursed to turn into a girl when splashed with cold water navigates love, rivalry, and chaos at home."
  },
  {
    id: "ranma-s2",
    title: "Ranma ½ (2024)",
    season: "Season 2",
    thumb: "https://i.imgur.com/P8wskkB.jpeg",
    genres: ["Action", "Comedy", "Romance"],
    run: "TV Series (2024)",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "7.8",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Ranma%20½%20Season%202%20Hindi",
    synopsis: "Ranma's chaotic life continues with new challengers, deeper rivalries, and no shortage of cold water."
  },
  {
    id: "aot-s1",
    title: "Attack on Titan",
    season: "Season 1",
    thumb: "https://iili.io/qEhW0jn.jpg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 25,
    subtitle: "English",
    quality: "480p / 720p / 1080p",
    rating: "9.1",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Attack%20on%20Titan%20Season%2001%20Hindi",
    synopsis: "Humanity huddles behind massive walls to survive against man-eating Titans, until one boy vows to wipe them all out."
  },
  {
    id: "aot-s2",
    title: "Attack on Titan",
    season: "Season 2",
    thumb: "https://iili.io/B0whE2p.jpg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "9.1",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Attack%20on%20Titan%20Season%2002%20Hindi",
    synopsis: "Secrets behind the Titans and the walls themselves begin to surface as old loyalties are tested."
  },
  {
    id: "aot-s3",
    title: "Attack on Titan",
    season: "Season 3",
    thumb: "https://i.imgur.com/FN1k1RS.jpeg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 22,
    subtitle: "English",
    quality: "720p",
    rating: "9.1",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Attack%20on%20Titan%20Season%2003%20Hindi",
    synopsis: "A government conspiracy unravels as the survey corps uncover the true history hidden beneath the walls."
  },
  {
    id: "aot-s4",
    title: "Attack on Titan",
    season: "Season 4",
    thumb: "https://i.imgur.com/AC4PhvA.jpeg",
    genres: ["Action", "Drama", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 28,
    subtitle: "English",
    quality: "720p",
    rating: "9.1",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Attack%20on%20Titan%20Season%2004%20Hindi",
    synopsis: "The final chapter brings the war to its devastating conclusion as Eren's true intentions are revealed."
  },
  {
    id: "jjk-s1",
    title: "Jujutsu Kaisen",
    season: "Season 1",
    thumb: "https://i.imgur.com/1DQVrEi.jpg",
    genres: ["Action", "Comedy", "Drama", "Fantasy", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.6",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Jujutsu%20kaisen%20Season%201%20in%20Hindi",
    synopsis: "A high schooler swallows a cursed object to save his friends and is drawn into the hidden world of curses and exorcists."
  },
  {
    id: "jjk-s2",
    title: "Jujutsu Kaisen",
    season: "Season 2",
    thumb: "https://i.imgur.com/24Sdguu.jpg",
    genres: ["Action", "Comedy", "Drama", "Fantasy", "Shounen"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 23,
    subtitle: "English",
    quality: "720p",
    rating: "8.8",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Jujutsu%20kaisen%20Season%202%20in%20Hindi",
    synopsis: "The Hidden Inventory and Shibuya Incident arcs unfold, reshaping the world of jujutsu sorcerers forever."
  },
  {
    id: "jjk-s3",
    title: "Jujutsu Kaisen",
    season: "Season 3",
    thumb: "https://iili.io/fsSZs5P.jpg",
    genres: ["Action", "Fantasy"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · Bangla · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "8.7",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Jujutsu%20kaisen%20Season%203%20in%20Hindi",
    synopsis: "The Culling Game arc begins, pitting sorcerers against each other in a deadly game with the fate of the world at stake."
  },
  {
    id: "jjk-0",
    title: "Jujutsu Kaisen 0",
    season: "Movie",
    thumb: "https://iili.io/KZU007a.jpg",
    genres: ["Action", "Supernatural"],
    run: "Movie",
    runtime: "1 hr 44 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: null,
    subtitle: "English",
    quality: "720p",
    rating: "7.8",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Jujutsu%20Kaisen%200%20Hindi",
    synopsis: "A young sorcerer cursed by a childhood promise must choose between vengeance and the bonds he forms at Jujutsu High."
  },
  {
    id: "slime-s1",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 1",
    thumb: "https://i.imgur.com/Djod0Lz.jpeg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.2",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=That%20Time%20I%20Got%20Reincarnated%20as%20a%20Slime%20Season%2001",
    synopsis: "Reincarnated as a slime in a fantasy world, an ordinary man builds a nation from scratch with unexpected power and diplomacy."
  },
  {
    id: "slime-s2",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 2",
    thumb: "https://i.imgur.com/P2XplVL.jpeg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.2",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=That%20Time%20I%20Got%20Reincarnated%20as%20a%20Slime%20Season%2002",
    synopsis: "Rimuru's nation of Tempest draws the attention of empires and threats far beyond the forest it began in."
  },
  {
    id: "slime-s3",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 3",
    thumb: "https://i.imgur.com/0ImlG4C.jpeg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.2",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=That%20Time%20I%20Got%20Reincarnated%20as%20a%20Slime%20Season%2003",
    synopsis: "Tempest's rise to nationhood accelerates as Rimuru faces rivals who see his peace as a threat."
  },
  {
    id: "slime-s4",
    title: "That Time I Got Reincarnated as a Slime",
    season: "Season 4",
    thumb: "https://iili.io/CKxKAmb.jpg",
    genres: ["Action", "Adventure", "Comedy", "Fantasy", "Isekai"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: null,
    subtitle: "English",
    quality: "480p / 720p / 1080p",
    rating: "8.2",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=That%20Time%20I%20Got%20Reincarnated%20as%20a%20Slime%20Season%2004",
    synopsis: "The next chapter of Tempest's story continues to expand the world Rimuru has built."
  }, 
  {
    id: "vinlandsaga-s1",
    title: "Vinland Saga",
    season: "Season 1",
    thumb: "https://i.imgur.com/tXnBhR1.jpg",
    genres: ["Animation", "Action", "Adventure"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.7",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Vinland%20Saga%20Season%2001%20Hindi",
    synopsis: "Thorfinn pursues a journey with his father’s killer in order to take revenge and end his life in a duel as an honorable warrior and pay his father a homage."
  }, 
  {
    id: "vinlandsaga-s2",
    title: "Vinland Saga",
    season: "Season 2",
    thumb: "https://i.imgur.com/NR6ybnc.jpg",
    genres: ["Animation", "Action", "Adventure"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 24,
    subtitle: "English",
    quality: "720p",
    rating: "8.9",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Vinland%20Saga%20Season%2002%20Hindi",
    synopsis: "Thorfinn pursues a journey with his father’s killer in order to take revenge and end his life in a duel as an honorable warrior and pay his father a homage."
  }, 
  {
    id: "sakamoto-days-s1",
    title: "Sakamoto Days",
    season: "Season 1",
    thumb: "https://i.imgur.com/2JgOLVl.jpeg",
    genres: ["Comedy", "Action"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · Tamil · Telugu · English · Japanese",
    episodes: 22,
    subtitle: "English",
    quality: "720p",
    rating: "7.5",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Sakamoto%20Days%20Season%201%20Hindi",
    synopsis: "The man who was feared by all villains, and revered by all hitmen, one day, fell in love. When Sakamoto met Aoi the convenience store clerk, it was love at first sight; and just like that, he retired, until . . ."
  },
  {
    id: "classroom-of-the-elite-s1",
    title: "Classroom of the Elite",
    season: "Season 1",
    thumb: "https://image.tmdb.org/t/p/w400/yuHanbUUIv2UWRxxQFt9n8jtmOJ.jpg",
    genres: ["Animation", "Drama", "Thriller"],
    run: "TV Series",
    runtime: "24 min",
    language: "Hindi · English · Japanese",
    episodes: 12,
    subtitle: "English",
    quality: "720p",
    rating: "8.49",
    platform: "Telegram",
    platformUrl: "/URLchecker.html?id=Classroom%20of%20the%20Elite%20Season%201%20Hindi",
    synopsis: "When Kiyotaka enters government-sponsored elite high school, he finds out just how merit-based this education system is."
  }, 
  {
  id: "classroom-of-the-elite-s2",
  title: "Classroom of the Elite",
  season: "Season 2",
  thumb: "https://image.tmdb.org/t/p/w400/lLD9Xg5bASKrUAp7bLCm7s8WbKW.jpg",
  genres: ["Drama", "School"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "720p",
  rating: "8.49",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Classroom%20of%20the%20Elite%20Season%202%20Hindi",
  synopsis: "Kiyotaka Ayanokoji continues navigating the ruthless Advanced Nurturing High School as new special exams and rivalries push Class D to its limits."
},
{
  id: "classroom-of-the-elite-s3",
  title: "Classroom of the Elite",
  season: "Season 3",
  thumb: "https://iili.io/qwzF4KF.jpg",
  genres: ["Drama", "School"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 13,
  subtitle: "English",
  quality: "720p",
  rating: "7.9",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Classroom%20of%20the%20Elite%20Season%203%20Hindi",
  synopsis: "The battle for Class A intensifies as Ayanokoji faces increasingly complex strategies, alliances, and betrayals."
},
{
  id: "lord-of-mysteries-s1",
  title: "Lord of Mysteries",
  season: "Season 1",
  thumb: "https://i.imgur.com/TM5wGL2.jpeg",
  genres: ["Action", "Fantasy", "Mystery"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Chinese",
  episodes: 13,
  subtitle: "English",
  quality: "720p",
  rating: "8.5",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Lord%20of%20Mysteries%20Season%2001%20Hindi",
  synopsis: "After awakening in a mysterious Victorian-inspired world, Klein Moretti becomes entangled in supernatural organizations and hidden powers."
},
{
  id: "devil-may-cry-s1",
  title: "Devil May Cry",
  season: "Season 1",
  thumb: "https://i.imgur.com/4LDErQA.jpeg",
  genres: ["Action", "Adventure", "Fantasy"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English",
  episodes: 8,
  subtitle: "English",
  quality: "720p",
  rating: "?",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Devil%20May%20Cry%20Season%201%20Hindi",
  synopsis: "The legendary demon hunter Dante takes on dangerous contracts while facing powerful enemies from the underworld."
},
{
  id: "sentenced-to-be-a-hero-s1",
  title: "Sentenced to Be a Hero",
  season: "Season 1",
  thumb: "https://iili.io/fjDzxtI.jpg",
  genres: ["Action", "Adventure", "Fantasy"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · Tamil · Telugu · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "?",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Sentenced%20to%20Be%20a%20Hero%20Season%201%20Hindi",
  synopsis: "Convicted criminals are forced into deadly battles against terrifying monsters, earning redemption only through survival."
},
{
  id: "tokyo-ghoul-s1",
  title: "Tokyo Ghoul",
  season: "Season 1",
  thumb: "https://iili.io/fwcucua.jpg",
  genres: ["Action", "Fantasy", "Horror"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.8",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Tokyo%20Ghoul%20Season%2001%20Hindi",
  synopsis: "After a tragic encounter, Ken Kaneki becomes half-ghoul and struggles to survive between the human and ghoul worlds."
},
{
  id: "tokyo-ghoul-s2",
  title: "Tokyo Ghoul √A",
  season: "Season 2",
  thumb: "https://iili.io/fieARwP.jpg",
  genres: ["Action", "Fantasy", "Horror"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 12,
  subtitle: "English",
  quality: "720p",
  rating: "7.8",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Tokyo%20Ghoul%20√A%20Season%2002%20Hindi",
  synopsis: "Kaneki joins Aogiri Tree and walks a darker path as conflict between ghouls and investigators escalates."
},
{
  id: "tokyo-ghoul-re-s1",
  title: "Tokyo Ghoul:re",
  season: "Season 3",
  thumb: "https://iili.io/qKybzSn.jpg",
  genres: ["Action", "Fantasy", "Horror"],
  run: "TV Series",
  runtime: "24 min",
  language: "Hindi · English · Japanese",
  episodes: 24,
  subtitle: "English",
  quality: "720p",
  rating: "6.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Tokyo%20Ghoul:re%20Season%2003%20Hindi",
  synopsis: "A mysterious investigator named Haise Sasaki leads a squad of Quinx while fragments of Kaneki's past begin to return."
},
{
  id: "tokyo-ghoul-jack",
  title: "Tokyo Ghoul: Jack",
  season: "Special",
  thumb: "https://iili.io/Bim98qQ.jpg",
  genres: ["Action", "Fantasy", "Horror"],
  run: "OVA",
  runtime: "30 min",
  language: "Hindi · Japanese",
  episodes: 1,
  subtitle: "English",
  quality: "720p",
  rating: "6.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Tokyo%20Ghoul:%20Jack%20Special%20Episode%20Hindi",
  synopsis: "A prequel following Kishou Arima and Taishi Fura as they investigate a deadly ghoul known as Lantern."
},
{
  id: "tokyo-ghoul-pinto",
  title: "Tokyo Ghoul: Pinto",
  season: "Special",
  thumb: "https://iili.io/B4Nf1iN.jpg",
  genres: ["Action", "Fantasy", "Horror"],
  run: "OVA",
  runtime: "25 min",
  language: "Hindi · Japanese",
  episodes: 1,
  subtitle: "English",
  quality: "720p",
  rating: "6.4",
  platform: "Telegram",
  platformUrl: "/URLchecker.html?id=Tokyo%20Ghoul%20Pinto%20Special%20Episode%20Hindi",
  synopsis: "A side story exploring the unusual relationship between Tsukiyama Shuu and photographer Chie Hori."
}
];
